parameters:
#    smart_information_systems_object_history.example.class: SmartInformationSystems\ObjectHistoryBundle\Example

services:
    smart_information_systems_object_history.doctrine.listener:
        class: SmartInformationSystems\ObjectHistoryBundle\EventListener\DoctrineListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
